# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c362bd6f5680232ff48faf16213aca733781c5ce86555c8cf66a5a5f11f58fb63e5a2a06fc135100e7ee7d3910719a8afb49c3874725e445edb6a3ee3a1b520b

test:
  secret_key_base: 6e86b6810043c00c6b857f2515997f9a8a921d1e754888884db943a7df9342ca90de4f18a370b33b48b81879f627d6c92c35e85d8d14ed007431374a8bff7e4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
